hildaweb/urls.py
import django
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

import movies

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('', RedirectView.as_view(url='movies/')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'movies.views.error_404'
handler500 = 'movies.views.error_500'
handler403 = 'movies.views.error_403'
handler400 = 'movies.views.error_400'

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]
    urlpatterns += [re_path(r'^500/$', movies.views.error_500)]
    urlpatterns += [re_path(r'^400/$', movies.views.error_400)]
    urlpatterns += [re_path(r'^404/$', movies.views.error_404)]
    urlpatterns += [re_path(r'^403/$', movies.views.error_403)]


admin.site.site_header = "MFD Administrace"
admin.site.site_title = "Malá filmová databáze"
admin.site.index_title = "Vítejte v administrační části MFD"

movies/urls.py
from django.urls import path, re_path
from . import views

# URL mapování - seznam URL adres pro aplikaci movies
urlpatterns = [
    path('', views.index, name='index'),
    path('films/', views.FilmListView.as_view(), name='films'),
    #re_path(r'^films/genres/(?P<genre_name>[\w-]+)/:?(?P<order>[\w-]*)$', views.FilmListView.as_view(), name='film_genre'),
    path('films/genres/<str:genre_name>/', views.FilmListView.as_view(), name='film-genre'),
    path('films/<int:pk>/', views.FilmDetailView.as_view(), name='film-detail'),
    path('films/create/', views.FilmCreate.as_view(), name='film-create'),
    path('films/<int:pk>/update/', views.FilmUpdate.as_view(), name='film-update'),
    path('films/<int:pk>/delete/', views.FilmDelete.as_view(), name='film-delete'),
    #path('films/<int:pk>/edit/', views.edit_film, name='film-edit'),
    path('clear_cache/', views.clear_cache),
]

movies/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from django.utils.html import format_html

""" Metoda vrací cestu k uploadovaným souborů - přílohám filmů.
    Cesta má obecnou podobu: film/id-filmu/attachments/nazev-souboru.
    Parametr instance odkazuje na instanci (objekt) filmu.
    Parametr filename obsahuje název uploadovaného souboru. """
def attachment_path(instance, filename):
    return "film/" + str(instance.film.id) + "/attachments/" + filename


class Genre(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name="Genre name",
                            help_text='Enter a film genre (e.g. sci-fi, comedy)')

    class Meta:
        # atribut ordering definuje upřednostňovaný způsob řazení - zde vzestupně podle pole/sloupce name
        ordering = ["name"]
        verbose_name = "Žánr"
        verbose_name_plural = "Žánry"

    def __str__(self):
        """ Řetězec, který se používá jako textová reprezentace objektu (například v administraci aplikace).
        V našem případě bude objekt (žánr) reprezentován výpisem obsahu pole name """
        return self.name

    def film_count(self, obj):
        return obj.film_set.count()

class Film(models.Model):
    # Fields
    # Znakové pole o maximální délce 200 znaků pro vložení názvu filmu
    title = models.CharField(max_length=200, verbose_name="Title")
    # Textové pole pro vložení delšího textu popisujícího děj filmu
    # Formulářový prvek může zůstat prázdný - parametry blank=True, null=True
    plot = models.TextField(blank=True, null=True, verbose_name="Plot")
    # Pole obsahuje datum uvedení filmu, které musí být zadáno v náležitém tvaru (YYYY-MM-DD); nepovinný údaj
    release_date = models.DateField(blank=True, null=True,
                                    help_text="Please use the following format: <em>YYYY-MM-DD</em>.",
                                    verbose_name="Release date")
    # Celočíselné pole pro nepovinné zadání stopáže (délky) filmu v minutách
    runtime = models.IntegerField(blank=True, null=True,
                                  help_text="Please enter an integer value (minutes)",
                                  verbose_name="Runtime")
    # Pole typu image, které umožňuje upload obrázku s plakátem filmu
    poster = models.ImageField(upload_to='film/posters/%Y/%m/%d/', blank=True, null=True, verbose_name="Poster")
    # Pole pro zadání desetinného čísla vyjadřujícího hodnocení filmu v rozsahu 1.0 až 10.0
    # Výchozí hodnota je nastavena na 5.0
    # K validaci hodnot jsou použity metody z balíku/knihovny django.core.validators
    rate = models.FloatField(default=5.0,
                             validators=[MinValueValidator(1.0), MaxValueValidator(10.0)],
                             null=True,
                             help_text="Please enter an float value (range 1.0 - 10.0)",
                             verbose_name="Rate")
    # Vytvoří vztah mezi modely Film a Genre typu M:N
    genres = models.ManyToManyField(Genre, help_text='Select a genre for this film')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # Metadata
    class Meta:
        # Záznamy budou řazeny primárně sestupně (znaménko mínus) podle data uvedení,
        # sekundárně vzestupně podle názvu
        ordering = ["-release_date", "title"]

    # Methods
    def __str__(self):
        """Součástí textové reprezentace filmu bude jeho název, rok uvedení a hodnocení"""
        return f"{self.title}, year: {str(self.release_date.year)}, rate: {str(self.rate)}"

    def get_absolute_url(self):
        """Metoda vrací URL stránky, na které se vypisují podrobné informace o filmu"""
        return reverse('film-detail', args=[str(self.id)])

    def release_year(self):
        return self.release_date.year

    def rate_percent(self):
        return format_html("{} %", int(self.rate * 10))


""" Třída Attachment je modelem pro databázový objekt (tabulku), který bude obsahovat údaje o přílohách filmů """

class Attachment(models.Model):
    # Fields
    # Povinný titulek přílohy - text do délky 200 znaků
    title = models.CharField(max_length=200, verbose_name="Title")
    # Časový údaj o poslední aktualizaci přílohy - automaticky se ukládá aktuální čas
    last_update = models.DateTimeField(auto_now=True)
    # Pole pro upload souboru
    # Parametr upload_to zajistí uložení souboru do složky specifikované v návratové hodnotě metody attachment_path
    file = models.FileField(upload_to=attachment_path, null=True, verbose_name="File")

    # Konstanta, v níž jsou ve formě n-tic (tuples) předdefinovány různé typy příloh
    TYPE_OF_ATTACHMENT = (
        ('audio', 'Audio'),
        ('image', 'Image'),
        ('text', 'Text'),
        ('video', 'Video'),
        ('other', 'Other'),
    )

    # Pole s definovanými předvolbami pro uložení typu přílohy
    type = models.CharField(max_length=5, choices=TYPE_OF_ATTACHMENT, blank=True, default='image', help_text='Select allowed attachment type', verbose_name="Attachment type")
    # Cizí klíč, který zajišťuje propojení přílohy s daným filmem (vztah N:1)
    # Parametr on_delete slouží k zajištění tzv. referenční integrity - v případě odstranění filmu
    # budou odstraněny i všechny jeho přílohy (models.CASCADE)
    film = models.ForeignKey(Film, on_delete=models.CASCADE)

    # Metadata
    class Meta:
        # Primární seřazeno podle poslední aktualizace souborů, sekundárně podle typu přílohy
        # ordering = ["-last_update", "type"]
        order_with_respect_to = 'film'

    # Methods
    def __str__(self):
        """ Textová reprezentace objektu """
        return f"{self.title}, ({self.type})"

    @property
    def filesize(self):
        x = self.file.size
        y = 512000
        if x < y * 1000:
            value = round(x/1024, 2)
            ext = ' KB'
        elif x < y * 1000**2:
            value = round(x/1024*2, 2)
            ext = ' MB'
        else:
            value = round(x/1024**3, 2)
            ext = ' GB'
        return str(value)+ext


class Review(models.Model):
    text = models.TextField(verbose_name="Text")
    edit_date = models.DateTimeField(auto_now=True)
    rate = models.IntegerField(default=5,
                             validators=[MinValueValidator(1), MaxValueValidator(10)],
                             null=True,
                             help_text="Please enter an integer value (range 1 - 10)",
                             verbose_name="Rate")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    film = models.ForeignKey(Film, on_delete=models.CASCADE)

    # Metadata
    class Meta:
        order_with_respect_to = 'film'

movies/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from .models import Genre, Film


class FilmModelForm(ModelForm):
    def clean_runtime(self):
       data = self.cleaned_data['runtime']
       if data <= 0 or data > 1000:
           raise ValidationError('Neplatná délka filmu')
       return data

    def clean_rate(self):
       data = self.cleaned_data['rate']
       if data < 1 or data > 10:
           raise ValidationError('Neplatné hodnocení: musí být v rozsahu 1-10')
       return data

    class Meta:
        model = Film
        fields = ['title', 'plot', 'poster', 'genres', 'release_date', 'runtime', 'rate']
        labels = {'title': 'Název filmu', 'plot': 'Stručný děj'}

"""
class FilmForm(forms.Form):
    title = forms.CharField(label='Název filmu', help_text='Zadejte název filmu', required=True)
    plot = forms.CharField(label='Stručný děj', required=False)
    release_date = forms.DateField(label='Datum uvedení', required=True)
    runtime = forms.IntegerField(label='Délka filmu', required=False, help_text='Uveďte počet minut')
    poster = forms.ImageField(label='Plakát', required=False, help_text='Vkládejte grafické formáty')
    FILM_RATE = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    )
    rate = forms.ChoiceField(choices=FILM_RATE, label='Hodnocení')
    genres = forms.ModelMultipleChoiceField(queryset = Genre.objects.all())
"""

movies/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Permission
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.decorators.cache import never_cache
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator

from movies.forms import FilmModelForm
from movies.models import Film, Genre, Attachment
#from .forms import FilmForm


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_films = Film.objects.all().count()
    films = Film.objects.order_by('-rate')[:3]

    context = {
        'num_films': num_films,
        'films': films
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class FilmListView(ListView):
    model = Film

    context_object_name = 'films_list'   # your own name for the list as a template variable
    template_name = 'film/list.html'  # Specify your own template name/location
    paginate_by = 3

    def get_queryset(self):
        if 'genre_name' in self.kwargs:
            return Film.objects.filter(genres__name=self.kwargs['genre_name']).all() # Get 5 books containing the title war
        else:
            return Film.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['num_films'] = len(self.get_queryset())
        if 'genre_name' in self.kwargs:
            context['view_title'] = f"Žánr: {self.kwargs['genre_name']}"
            context['view_head'] = f"Žánr filmu: {self.kwargs['genre_name']}"
        else:
            context['view_title'] = 'Filmy'
            context['view_head'] = 'Přehled filmů'
        return context

class FilmDetailView(DetailView):
    model = Film

    context_object_name = 'film_detail'   # your own name for the list as a template variable
    template_name = 'film/detail.html'  # Specify your own template name/location


class GenreListView(ListView):
    model = Genre
    template_name = 'blocks/genre_list.html'
    context_object_name = 'genres'
    queryset = Genre.objects.order_by('name').all()


class TopTenListView(ListView):
    model = Film
    template_name = 'blocks/top_ten.html'
    context_object_name = 'films'
    queryset = Film.objects.order_by('-rate').all()[:10]


class NewFilmListView(ListView):
    model = Film
    template_name = 'blocks/new_films.html'
    context_object_name = 'films'
    queryset = Film.objects.order_by('release_date').all()
    paginate_by = 2


class FilmCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Film
    fields = ['title', 'plot', 'release_date', 'runtime', 'poster', 'rate', 'genres']
    initial = {'rate': '5'}
    login_url = '/accounts/login/'
    permission_required = 'movies.add_film'


class FilmUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Film
    template_name = 'movies/film_bootstrap_form.html'
    form_class = FilmModelForm
    login_url = '/accounts/login/'
    permission_required = 'movies.change_film'


class FilmDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Film
    success_url = reverse_lazy('films')
    login_url = '/accounts/login/'
    permission_required = 'movies.delete_film'


def error_404(request, exception=None):
        return render(request, 'errors/404.html')

def error_500(request):
    return render(request, 'errors/500.html')

def error_403(request, exception=None):
    return render(request, 'errors/403.html')

def error_400(request, exception=None):
    return render(request, 'errors/400.html')

@never_cache
def clear_cache(request):
    if not request.user.is_superuser:
        raise PermissionDenied
    cache.clear()
    return HttpResponse('Cache has been cleared')

movies/templates/film/detail.html
{% extends "base.html" %}
{% block title %}Detail filmu{% endblock %}
{% block css %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col-sm-12 bg-warning">
        <h2 class="display-4 text-center">Podrobné informace</h2>
    </div>
</div>
<div class="row mt-5 mb-3">
    <div class="col-lg-6 mb-3">
        <h2 class="display-4 mb-3">{{ film_detail.title }}</h2>
        <div class="bg-secondary text-light p-2 mb-3">Rok vzniku: {{ film_detail.release_date.year }}, stopáž: {{ film_detail.runtime }} minut,
            {% with ''|center:film_detail.rate as range %}
            {% for _ in range %}★{% endfor %}
            {% endwith %}
            <b>{{ film_detail.rate }}</b>
        </div>
        <div class="row">
            <div class="col-md-9">{{ film_detail.plot }}</div>
            <div class="col-md-3">
                {% if film_detail.poster %}
                <a href="{{ film_detail.poster.url }}" data-toggle="lightbox" data-gallery="gallery">
                    <img src="{{ film_detail.poster.url }}" class="img-fluid" alt="Plakát k filmu">
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-lg-6 bg-light p-3">
        <h3 class="border-bottom pb-3 text-secondary text-center text-uppercase">Fotogalerie</h3>
        <div class="row">
        {% for image in film_detail.attachment_set.all %}
            <div class="col-lg-6 col-xl-4">
                <a href="{{ image.file.url }}" data-toggle="lightbox" data-gallery="gallery">
                    <img src="{{ image.file.url }}" class="img-fluid img-thumbnail" alt="{{ image.title }}">
                </a>
            </div>
        {% endfor %}
        </div>
    </div>
    <div class="col-lg-12 mb-3 bg-info text-white">
        <h3 class="text-center p-3">Recenze</h3>
    </div>
    <div class="col-lg-12 mb-3">
        {% for review in film_detail.review_set.all %}
            <h4>{% if review.author.profile.avatar %}<img src="{{ review.author.profile.avatar.url }}" alt="{{ review.author.user.prijmeni }}" class="rounded-circle" width="50">{% endif %}{{ review.author }} {{ review.edit_date }}</h4>
            <p>{{ review.text }}</p>
            <hr>
        {% endfor %}
    </div>
</div>
{% if user.is_authenticated %}
<div class="row mb-3">
    <div class="col-sm-12 text-center">
        <a href="{% url 'film-update' film_detail.pk %}" class="btn btn-primary">Upravit</a>
    {% if perms.movies.delete_film %}
        <a href="{% url 'film-delete' film_detail.pk %}" class="btn btn-danger">Smazat</a>
    {% endif %}
    </div>
</div>
{% endif %}
{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js"></script>
<script>
    $(document).on("click", '[data-toggle="lightbox"]', function(event) {
        event.preventDefault();
        $(this).ekkoLightbox();
    });
</script>
{% endblock %}

movies/templates/film/genre.html
{% extends "base.html" %}
{% block title %}Seznam filmů{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h2>Seznam filmů: {{ view.kwargs.genre_name }}</h2>
    </div>
</div>
<div class="row">
    {% for film in film_genre %}
    <div class="col-sm-6 col-md-4 col-lg-3 col-xl-2">
        <div class="card">
            {% if film.poster %}
            <img class="card-img-top" src="{{ film.poster.url }}" alt="{{ film.title }}">
            {% endif %}
            <div class="card-body">
                <h4 class="card-title"><a href="{% url 'film-detail' film.pk %}">{{ film.title }}</a></h4>
                <p class="card-text">{% for genre in film.genres.all %}<a href="{% url 'film-genre' genre.name %}" class="btn btn-info">{{ genre.name }}</a> {% endfor %}</p>
                <a href="{% url 'film-detail' film.pk %}" class="btn btn-primary">Podrobnosti</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="row">
    <div class="col-sm-12">
        <strong>Celkový počet filmů:</strong> {{ num_films }}
    </div>
</div>
{% endblock %}

movies/templates/film/list.html
{% extends "base.html" %}
{% load bootstrap_pagination %}
{% block title %}{{ view_title }}{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col-sm-12 bg-warning">
        <h2 class="display-4 text-center">{{ view_head }}</h2>
    </div>
</div>
<div class="row">
    {% for film in films_list %}
    <div class="col-sm-6 col-md-4 col-lg-3 col-xl-2">
        <div class="card">
            {% if film.poster %}
            <img class="card-img-top" src="{{ film.poster.url }}" alt="{{ film.title }}">
            {% endif %}
            <div class="card-body">
                <h4 class="card-title"><a href="{% url 'film-detail' film.pk %}">{{ film.title }}</a></h4>
                <p class="card-text">{% for genre in film.genres.all %}<a href="{% url 'film-genre' genre.name %}" class="btn btn-light">{{ genre.name }}</a> {% endfor %}</p>
            {% if user.is_authenticated %}
                <a href="{% url 'film-detail' film.pk %}" class="btn btn-primary">Podrobnosti</a>
            {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% if is_paginated %}
<div class="row mt-5">
    <div class="col-12">
    {% bootstrap_paginate page_obj range=10 %}
    </div>
</div>
{% endif %}
<div class="row mt-3">
    <div class="col-sm-12">
        <h4>Celkový počet filmů: {{ num_films }}</h4>
    </div>
</div>
{% if perms.movies.can_add_film %}
<div class="row mb-3">
    <div class="col-sm-12 text-center">
        <a href="{% url 'film-create' %}" class="btn btn-success">Nový film</a>
    </div>
</div>
{% endif %}
{% endblock %}